### ISSUE TITLE
Splitting frontend ouf of the current application and modularisation of TEXTUS architecture 

### ISSUE THREAD

**Issue by noelmas** [rufuspollock-okfn/textus#37]
1) Splitting the frontend out of the current application -- separating
the "Reader UI" from the "TEXTUS API".

2) Modularisation of the architecture of the two resulting applications.
On the backend this is probably less of an issue, but on the frontend,
we need to work out how the CSS for individual deployments
(OpenPhilosophy, OpenShakespeare, etc.) gets applied and how the
"Reader" fits into all the other content that would likely exist on
those sites.

**Comment by tomoinn** [comment]
For 1) this is already how it works, all the HTML and client side javascript is in src/public. For 2) textus actually has very little css of its own, really just some work-arounds for things that are broken in bootstrap on narrow screens and support for its implementation of the modal dialogue box.

All the pages are based on HTML template fragments loaded in dynamically with require.js, so for example editing the front page text is just a question of editing that particular template. Custom logos and welcome text are simple therefore. We use a slightly modified bootstrap CSS, modified because the default looks terrible with a pale nav bar (it uses shadows which look good with the dark one but very fuzzy otherwise), but few other changes so you could just drop in a new theme and expect everything to work. Other than that individual texts have stable URLs, so you could create your own index in e.g. wordpress, disable all functionality other than the reader and login pages (by removing their links from the top level template) and link directly into the texts from whatever site you were using.
